#    'inicial' : {'txt' : 'Bem vindo ao teste 1, mortal.',
#        'spd' : '100',
#        'choicetxt' : 'I will choose... ',
#        '1' : 'roomifchoice1',
#        '2' : 'roomifchoice2',
#        '3' : 'roomifchoice3',
#        '4' : 'roomifchoice4'},
rooms = {
    'inicial' : {'txt' : 'Bem vindo ao jogo1, mortal.',
        'spd' : 100,
        'choicetxt' : 'I will choose... ',
        '1' : 'sala1',
        '2' : 'sala2',
        '3' : 'sala3',
        '4' : 'sala4',},
    'sala1' : {'txt' : 'Bem vindo a sala1, mortal.',
        'spd' : 100,
        'choicetxt' : 'I will choose... ',
        '1' : 'roomifchoice1',
        '2' : 'roomifchoice2',
        '3' : 'roomifchoice3',
        '4' : 'roomifchoice4'},
    'sala2' : {'txt' : 'Bem vindo ao sala2, mortal.',
        'spd' : 100,
        'choicetxt' : 'I will choose... ',
        '1' : 'roomifchoice1',
        '2' : 'roomifchoice2',
        '3' : 'roomifchoice3',
        '4' : 'roomifchoice4'},
    'sala3' : {'txt' : 'Bem vindo ao sala3, mortal.',
        'spd' : '100',
        'choicetxt' : 'I will choose... ',
        '1' : 'roomifchoice1',
        '2' : 'roomifchoice2',
        '3' : 'roomifchoice3',
        '4' : 'roomifchoice4'},
    'sala4' : {'txt' : 'Bem vindo ao sala4, mortal.',
        'spd' : 100,
        'choicetxt' : 'I will choose... ',
        '1' : 'roomifchoice1',
        '2' : 'roomifchoice2',
        '3' : 'roomifchoice3',
        '4' : 'roomifchoice4'},
    }
